### ISSUE TITLE
DisplayName is not shown in the report for tests with @ParameterizedTest annotation in Juni5

### ISSUE THREAD

**Issue by BandyaDhapate** [allure-framework/allure-java#363]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?
Correct @DisplayName text is not captured in the report for the test methods annotated  with @ParameterizedTest instead text from @ValueSource/@CsvSource  is displayed as test's display name in the report.. 
@DisplayName text shows up for tests with @Test annotation. If same class has methods with @Test and @ParametrizedTest then correct DisplayName text only shows for @Test methods and not for @ParameterizedTest methods. 

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. Create a class with 2 test methods one annotated with @Test and another with @ParameterizedTest. 
2. Write @DisplayName for both tests. 
3. Execute Test gradle task
4. Check the report 

#### What is the expected behavior?
@DisplayName text shall appear for all active test method annotations supported by Junit5. 
E.g. @Test,@ParameterizedTest, @RepeatedTest

#### What is the motivation / use case for changing the behavior?
Improve readability of the test report when tests are annotated other than @Test

#### Please tell us about your environment:
Selenium, Junit5, Gradle, Java

| Allure version | 2.7.0 |
| --- | --- |
| Test framework | JUnit5 |
| Allure integration | allure-junit5@2.11.0 |
| Generate report using | allure-gradle@2.5 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by Chegodaeva** [comment]
I have the same problem. Please, fix it.

**Comment by kathyrollo** [comment]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
- `@DisplayName` is captured at class level.
- `@DisplayName` is ignored at test level with annotation `@ParameterizedTest`.


#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
```
@Tag("term-deposits")
@DisplayName("Term Deposits Test")
public class TermDepositsTest extends BaseTest {

    @ParameterizedTest
    @Tag("TC01")
    @DisplayName("Verify Total Interest")
    @Description("Verify computation of total interest and total end term with specified deposit amount and investment term.")
    @CsvFileSource(resources = "/app/TC01.csv", numLinesToSkip = 1)
    public void verifyTotalInterest(String deposit, String term) {
        // Do something
    }

}
```

Output:

![allure_issue](https://user-images.githubusercontent.com/28589393/79060343-48cdbb80-7cc7-11ea-8005-2edc1c7b8d23.PNG)


#### What is the expected behavior?
```
Term Deposits Test
  #1 Verify Total Interest - [1] 999, 3 Months
  #2 Verify Total Interest - [2] 1000, 6 Months
  ...
```

#### What is the motivation / use case for changing the behavior?
Improved readability for a business-facing report. Stakeholder was quick to point this out during demo.

#### Please tell us about your environment:


| Allure version | 2.13.2 |
| --- | --- |
| Test framework | junit@5.6.2 |
| Allure integration | allure-junit5@2.13.2 |
| Generate report using | allure-maven@2.10.0 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)
Also consider multiple tests in 1 test class e.g. 1 `@Test` and 1 `@ParameterizedTest` in the same class.

**Comment by kathyrollo** [comment]
I found the solution in the JUnit 5 documentation. This was not an issue with Allure.

### JUnit 5

```
@Tag("term-deposits")
@DisplayName("Term Deposits Test")
public class TermDepositsTest extends BaseTest {

	@ParameterizedTest(name = "Verify Total Interest - Deposit = {0}, Term = {1}")
	@Tag("TC01")
	@Description("Verify computation of total interest and total end term with specified deposit amount and investment term.")
	@CsvFileSource(resources = "/app/TC01.csv", numLinesToSkip = 1)
	public void verifyTotalInterest(String deposit, String term) {
		// Do something
	}

}
```

Source: https://junit.org/junit5/docs/snapshot/user-guide/#writing-tests-annotations

### Output

![parameterized_test_names](https://user-images.githubusercontent.com/28589393/80170382-21fa7800-862b-11ea-88c3-e4f4d7c721e2.PNG)

**Comment by martinsefcik** [comment]
I still think it's a bug in Allure.

In JUnit5 in case of parametrized test `DisplayName` is meant as name of test for all parametrized cases and `ParametrizedTest.name` is meant as "subtitle" for one specific case. You can see it by how the default value for name is defined. it contains only index and arguments, and not displayname placeholder.

And usually in junit reports it is visualized and grouped like this:

DisplayName
  |- ParametrizedTest.name for case one
  |- ParametrizedTest.name for case two
  |- ParametrizedTest.name for case three

In case Allure is not grouping parametrized test cases but display all of them as individual tests then I would expect that it will be visualized in report like this:

- DisplayName + ParametrizedTest.name for case one
- DisplayName + ParametrizedTest.name for case two
- DisplayName + ParametrizedTest.name for case three

So in case both annotations are defined they are concatenated.
