### ISSUE TITLE
Allure2 report do NOT support for cross browser testing

### ISSUE THREAD

**Issue by dilshan5** [allure-framework/allure-java#381]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ x] bug report

#### What is the current behavior?
 I use allure report for cross browser testing. Even though the all tests execute in different browsers at the same time but the the report shows only one browser. I used 'AllureCucumber4Jvm'

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
https://github.com/dilshan5/ttaf-ui-intive
Sample code is uploaded 

#### What is the expected behavior?
Should display test results for all the browsers which i have executed

#### What is the motivation / use case for changing the behavior?
Allure support for cross browser testing

#### Please tell us about your environment:

        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-cucumber4-jvm</artifactId>
            <version>2.12.1</version>
        </dependency>

#### Other information 
     <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.20</version>
                <configuration>
                    <argLine>
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                        -Dcucumber.options="--plugin io.qameta.allure.cucumber4jvm.AllureCucumber4Jvm"
                    </argLine>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by dilshan5** [comment]
Hi,
Is there any update on this?

**Comment by dilshan5** [comment]
attached allure-results folder 
[allure-results.zip](https://github.com/allure-framework/allure-java/files/3509320/allure-results.zip)

**Comment by auto-qa-git** [comment]
Hello, I am trying to do the same thing: See the test reports for each browser using Allure. 
Any solutions?

**Comment by anshuljayn** [comment]
Hi, I am facing the same issue. The last execution overrides the previous execution results. Is there any solution. This is preventing me to execute the multi-browser test (at-least from the reporting point of view)

**Comment by motivatedmind** [comment]
same thing with io.qameta.allure.cucumber5jvm.AllureCucumber5Jvm. No cross browser support yet

**Comment by vnpt73** [comment]
Hello is there any update? I'm also facing the same issue

**Comment by Davidvasantharaj** [comment]
Hi, any update on the cross browser issue ? I'm also facing the same issue.

**Comment by itkhanz** [comment]
Hi, Is there any solution to this issue yet? I am facing the same issue of cross-browser parallel testing with Cucumber where if the scenarios are run in parallel on multiple browsers then the tests are put under Retries tab. I am running my tests with following dependecies:

- Selenium Java 4.6
- Cucumber-TestNG 7.9
- TestNG 7.9
- allure-cucumber7-jvm

Below is how my Test suite looks like

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Smoke Test Suite" thread-count="10" parallel="tests">
    <listeners>
        <listener class-name="framework.listeners.ScenariosParallelTransformer"/>
    </listeners>
    <test  name="Chrome Browser Test">
        <parameter name="browser" value="chrome"/>
        <classes>
            <class name="framework.runners.BaseTestNGRunnerTest"/>
        </classes>
    </test> <!-- Test -->

    <test  name="Firefox Browser Test">
        <parameter name="browser" value="chrome"/>
        <classes>
            <class name="framework.runners.BaseTestNGRunnerTest"/>
        </classes>
    </test> <!-- Test -->
</suite> <!-- Suite -->
```

As you can see that I am runnin the same `BaseTestNGRunnerTest `on chrome and firefox in parallel.
What actually happens is that if the scenario and/or feature name is same, then the tests are put under Retries Tab in the Test Report for the corresponding scenario, instead of showing it as separate test. In the below pictures you can see that it shows two tests, one as the main test and other as Retry. To differentiate between browsers, I added logs in Hooks.

![chrome test](https://user-images.githubusercontent.com/62521743/209882306-d4fb063c-6ebb-4673-85dc-bd3e59b1cd1b.JPG)
![firefox test](https://user-images.githubusercontent.com/62521743/209882308-b3ab226c-bb9c-4b9c-8290-b75454e747fb.JPG)

The Timeline clearly shows the 6 tests running in parallel
![timeline](https://user-images.githubusercontent.com/62521743/209882309-7ddc599a-3cca-4429-87d6-4f7bcd1ddcd2.JPG)

but the dashboard and other tabs only shows 3 tests, and mark the remaining 3 tests as Retries. 

**Expected Behavior:**
Each Test should be reported as separate test in cross browser parallel testing even if the scenario/feature name is same

**Actual Behavior:**
Tests with same scenario/feature in cross browser parallel testing are shown as same test and the remaining executions of the scenario are put under Retries.

There is also a question for this on Stackoveflow
https://stackoverflow.com/questions/58417607/allure-cucumber-jvm-report-for-cross-browser-and-parallel-execution

**Comment by DilipMeghwal** [comment]
Any work-around or solution for this issue?

**Comment by nickator** [comment]
Any update on this issue? Quite an old issue and a basic requirement to display results based on the web browser.. Serenity uses "tags" to do this. But no matter what I've tried, like changing the report name based on the web browser, adding dynamic epics, suits, etc... it always adds the test under "Retries" and doesn't display it separately.

**Comment by standbyoneself** [comment]
> workaround: change **historyId**, but keep there some logic to get everytime same ID + browser name to see history for the test case e.g:
> 
> ```
> @Story("Your Story Name")
> @Test
>  public void loginStandardUser() {
>        updateTestNameForAllure(browserPrefix() + "YourStoryName");
>        standardUserActions.loginAction();
>  }
> 
> private void updateTestNameAndHistoryIdForAllure(String newName) {
>        Allure.getLifecycle().updateTestCase(testResult -> testResult.setName(newName));
>        String customHistoryId = Utils.generateConsistentHistoryId(newName, getBrowserName());
>        Allure.getLifecycle().updateTestCase(testResult -> testResult.setHistoryId(customUUID));
> }
> 
> privat String generateConsistentHistoryId(String newName, String browserName) {
>        String baseString = newName + browserName;
>        return UUID.nameUUIDFromBytes(baseString.getBytes()).toString();
>  }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/22882051/276169349-8136e6fb-72a2-4bba-880c-d77405eb6848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTUxMTEsIm5iZiI6MTcxNDk5NDgxMSwicGF0aCI6Ii8yMjg4MjA1MS8yNzYxNjkzNDktODEzNmU2ZmItNzJhMi00YmJhLTg4MGMtZDc3NDA1ZWI2ODQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDExMjY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZjBkZTU2ZDBjZTBhMDE4MDUzZWE5ZjRjMWZmYzQ5NTM0YzBmZDk5MmI2MDU3Mzg1MjhjMDNhNTJlNTNiYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SRFI7OO-pSwUUm0F37d_IzoR-XiWE6bnRnP2inoekCA)

Thanks, it works 🕺
