### ISSUE TITLE
Allure cannot detect proper junit5 lifecycle flow: missing  BeforeAllCallback and AfterAllCallback

### ISSUE THREAD

**Issue by mszajowskiwr** [allure-framework/allure-java#677]
**Describe the bug**
The allure reports do not contain attachments added in `BeforeAllCallback`/`AfterAllCallback`

**To Reproduce**
Run the following code with junit 5:

```java
import io.qameta.allure.Allure;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.AfterAllCallback;
import org.junit.jupiter.api.extension.AfterEachCallback;
import org.junit.jupiter.api.extension.AfterTestExecutionCallback;
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.BeforeEachCallback;
import org.junit.jupiter.api.extension.BeforeTestExecutionCallback;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.extension.ExtensionContext;

@ExtendWith({AllureIssueExtension.class})
public class AllureIssueTest {

    @BeforeAll
    static void beforeAll() {
        Allure.addAttachment("static beforeAll in test class", "something");
    }

    @BeforeEach
    void beforeEach() {
        Allure.addAttachment("beforeEach in test class", "something");
    }

    @Test
    void someTest() {
        Allure.addAttachment("someTest in test class", "something");
    }

    @AfterEach
    void afterEach() {
        Allure.addAttachment("afterEach in test class", "something");
    }

    @AfterAll
    static void afterAll() {
        Allure.addAttachment("static afterAll in test class", "something");
    }
}

class AllureIssueExtension implements BeforeAllCallback, BeforeEachCallback, BeforeTestExecutionCallback,
    AfterTestExecutionCallback, AfterEachCallback, AfterAllCallback {

    @Override
    public void beforeAll(final ExtensionContext context) {
        Allure.addAttachment("BeforeAllCallback in AllureIssueExtension", "something");
    }

    @Override
    public void beforeEach(final ExtensionContext context) {
        Allure.addAttachment("BeforeEachCallback in AllureIssueExtension", "something");
    }

    @Override
    public void beforeTestExecution(final ExtensionContext context) {
        Allure.addAttachment("BeforeTestExecutionCallback in AllureIssueExtension", "something");
    }

    @Override
    public void afterTestExecution(final ExtensionContext context) {
        Allure.addAttachment("AfterTestExecutionCallback in AllureIssueExtension", "something");
    }

    @Override
    public void afterEach(final ExtensionContext context) {
        Allure.addAttachment("AfterEachCallback in AllureIssueExtension", "something");
    }

    @Override
    public void afterAll(final ExtensionContext context) {
        Allure.addAttachment("AfterAllCallback in AllureIssueExtension", "something");
    }
}
```

**Expected behavior**
There should be 11 attachments in the allure report.

**Actual behavior**
The attachments made in `BeforeAllCallback` and `AfterAllCallback` are missing:

**Screenshots**
![image](https://user-images.githubusercontent.com/56036647/140314773-1a3455f5-0644-4cea-9dd9-1cc3e6c180d3.png)

**Additinal context**
It seems that the allure lifecycle is not started when the extensions are working. Here are the logs produced during `BeforeAllCallback` and `AfterAllCallback` work:

```
[ForkJoinPool-1-worker-3] ERROR AllureLifecycle - Could not add attachment: no test is running
```

**Comment by baev** [comment]
I don't think it is possible due to the limitations of callbacks API (there is no callbacks interceptor available). 

Each callbacks make it into the test body because they are executed after the test-started platform event & before the test-stoped platform event. 

Usually, it is not a good idea to use extension points to add data to the reports (e.g., using listeners to add screenshots on test failure) due to the lack of interceptors (extension points for Allure to catch the execution of your extension). And even if the framework introduces a new extension point to do so, nothing will prevent other users from using it to add more report data (ops, recursion).

To solve that particular issue, Allure has LifecycleListner (to interact with the report data within Allure Lifecycle). See https://github.com/orgs/allure-framework/discussions/1741#discussioncomment-8049478 as an example of using StepLifecycleListener
