### ISSUE TITLE
🐞: Spock2 BDD blocks missing from Allure report when dependencies in specific order

### ISSUE THREAD

**Issue by karltiirik** [allure-framework/allure-java#928]
### What happened?

Project setup: Maven, Groovy, Spock2, Allure

Reproduction steps:
1. Project: https://github.com/karltiirik/spock-restassured-allure/commit/30ff03c2ec7b577b0eae908c8ea9444b8e4511e0
2. Run tests `./mvnw clean test`
3. Serve Allure report `./mvnw allure:serve`
4. Spock2 BDD steps present in the report 
5. Change Spock2 and Allure dependency order: https://github.com/karltiirik/spock-restassured-allure/commit/4139b76949c31c0ec7ef143d9ceb639ea6878565
6. Run tests `./mvnw clean test`
7. Serve Allure report `./mvnw allure:serve`

Expected:
![Kuvatõmmis 2023-06-16 140234](https://github.com/allure-framework/allure-java/assets/6077967/ba159c8c-0da7-41ed-bc9c-58da6f7408a1)

Actual:
![Kuvatõmmis 2023-06-16 141218](https://github.com/allure-framework/allure-java/assets/6077967/b28e5100-04e5-45e9-9633-18aa32eb4792)

### What Allure Integration are you using?

allure-rest-assured, allure-spock2

### What version of Allure Integration you are using?

2.22.2

### What version of Allure Report you are using?

2.22.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karltiirik** [comment]
https://github.com/allure-framework/allure-java/issues/871 is possibly related to this issue.

**Comment by baev** [comment]
Steps blocks will appear in the report only if `allure-spock2` is located in the classpath before spock dependencies. The reason is that Spock uses labels on statements (from GOTO times) to mark the blocks. And then Spock groovy processor rewrites such statements. And after rewriting, labels are gone. Allure Spock integration uses the same processor to insert steps before statements with such labels, although if Spock processes the file first, labels are gone, and there is nothing we can do about it. 

According to the `ASTTransformation` docs, there is no way to specify the order of execution, although, at the moment, it seems that transformations are applied in the order they are discovered, which is the order they are located in the classpath. Both Maven & Grade build classpaths from top to bottom, so declaring allure-spock2 dependency first should do the trick.

**Comment by karltiirik** [comment]
@baev thank you for the in-depth answer! Will just add a comment that allure-spock2 dep will need to be defined before the spock dependency.
